[options]
admin_passwd = admin@odoo2024
db_host = localhost
db_port = 5432
db_user = odoo17
db_password = odoo17pass
addons_path = D:/odoo/community/addons,D:/odoo/community/odoo/addons,D:/odoo/oca/account-financial-tools,D:/odoo/oca/account-financial-reporting,D:/odoo/oca/reporting-engine,D:/odoo/oca/server-ux
xmlrpc_port = 8017
logfile = D:/odoo/odoo.log
log_level = info
bin_path = C:/Program Files/wkhtmltopdf/bin
data_dir = D:/odoo/data
